Error message args for ExceptionDetail
damianwajser/spring-commons pull request #144
Opened 2021-12-23 03:12 UTC by carolusquintus

Adding management for errorMessage arguments on BadRequestException as first approach.

2021-12-23 11:51 UTC, damianwajser requested changes
Muy bueno el PR, a penas esten los cambios lo mergeo.

2021-12-23 11:51 UTC, damianwajser commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/RestException.java
> +	protected RestException(String errorCode, String errorMessage, Object[] messageArgs, Optional<Object> errorDetail) {
poner los Object... messageArgs sobre el final de los argumentol, para respertar el orden de los parametros, al igual que en el constructor anterior.

2021-12-23 11:51 UTC, damianwajser commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/RestException.java
> +	protected RestException(String errorCode, String errorMessage, Object[] messageArgs, Optional<Object> errorDetail, Exception e) {
poner los Object... messageArgs sobre el final de los argumentol, para respertar el orden de los parametros, al igual que en el constructor anterior.

2021-12-23 11:51 UTC, damianwajser commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/impl/badrequest/BadRequestException.java
> +	public BadRequestException(String errorCode, String errorMessage, Object... messageArgs) {
Si lo haces para badRequest, y lo agregas en RestException, lo deberias hacer para todas las exceptions

2021-12-23 11:53 UTC, damianwajser commented
Adicionalmente por favor agregar esta nueva funcionalidad en el README.MD

2021-12-23 19:49 UTC, carolusquintus commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/RestException.java
> +	protected RestException(String errorCode, String errorMessage, Object[] messageArgs, Optional<Object> errorDetail, Exception e) {
El orden lo dejé de tal forma que `errorMessage` y `messageArgs`, estén juntos. También pensando en no alterar los constructores "legados"/actuales.
Pienso en las sig. alternativas:

- `protected RestException(String errorCode, String errorMessage, Object[] messageArgs, Optional<Object> errorDetail, Exception e)`
- `protected RestException(String errorCode, String errorMessage, Optional<Object> errorDetail, Exception e, Object... messageArgs)`
- `protected RestException(String errorCode, Optional<Object> errorDetail, Exception e, String errorMessage, Object... messageArgs)`

2021-12-23 19:50 UTC, carolusquintus commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/impl/badrequest/BadRequestException.java
> +	public BadRequestException(String errorCode, String errorMessage, Object... messageArgs) {
De acuerdo. Sólo quería hacer un primer acercamiento y tener tu punto de vista para el resto de exceptions.

2021-12-23 19:56 UTC, carolusquintus commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/model/ExceptionDetail.java
> +						   Optional<Object> detail) {
¿Opinas que sería mejor cambiar el constructor a usar `varargs` y que todos las clases lo usen por igual?
```
public ExceptionDetail(String errorCode, Optional<Object> detail, String errorMessage, Object... messageArgs) {
```

2021-12-23 20:28 UTC, damianwajser commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/RestException.java
> +	protected RestException(String errorCode, String errorMessage, Object[] messageArgs, Optional<Object> errorDetail, Exception e) {
no es alterar los actuales es agregar sobre el final los varargs.. es una buena practica, si no encontras la forma no pasa nada, pero seria interesante preservar esa buena practica.

2021-12-23 20:28 UTC, damianwajser commented on spring-commons-exception/src/main/java/com/github/damianwajser/exceptions/impl/badrequest/BadRequestException.java
> +	public BadRequestException(String errorCode, String errorMessage, Object... messageArgs) {
perfecto.. resolvamos la firma de los constructores y entendido... me gusta la idea.

2021-12-24 13:58 UTC, damianwajser approved these changes

2021-12-24 13:59 UTC, merged

2021-12-27 13:16 UTC, damianwajser commented
Subido a Maven Central... version 1.24.2 lista para usarse