add timeout configuration properties to resttemplate
damianwajser/spring-commons pull request #83
Opened 2020-09-07 22:08 UTC by facuc28

- Pending to add unit test coverage

2020-09-08 11:50 UTC, damianwajser requested changes

2020-09-08 11:50 UTC, damianwajser commented on spring-commons-rest-templates/src/main/java/com/github/damianwajser/rest/properties/TimeoutConfigurationProperties.java
> +@ConfigurationProperties(prefix = "rest.template.timeout")
spring-commons.rest.template.timeout

2020-09-08 11:50 UTC, damianwajser commented on spring-commons-rest-templates/src/main/java/com/github/damianwajser/rest/templates/RestTemplateConfiguration.java
> +	private int getValueWithDefault(final int value, final int defaultValue) {
Los defaults se hacen con la clase RestTemplateConfiguration levantando del classpath un properties con configs por defecto, te podes fijar en el proyecto spring-commons-cache los archivos spring-commons-cache.properties y  PropertiesCommonsCache

2020-09-08 11:50 UTC, damianwajser commented on spring-commons-rest-templates/src/main/java/com/github/damianwajser/rest/properties/TimeoutConfigurationProperties.java
> +package com.github.damianwajser.rest.properties;
Faltan tests

2020-09-08 12:44 UTC, facuc28 commented on spring-commons-rest-templates/src/main/java/com/github/damianwajser/rest/properties/TimeoutConfigurationProperties.java
> +@ConfigurationProperties(prefix = "rest.template.timeout")
Veo que en otros archivos lo tenes asi `"spring.commons.cache.enabled"` preferis ese formato ?

2020-09-08 12:50 UTC, damianwajser requested changes

2020-09-08 12:50 UTC, damianwajser commented on spring-commons-rest-templates/src/main/java/com/github/damianwajser/rest/properties/TimeoutConfigurationProperties.java
> +@ConfigurationProperties(prefix = "rest.template.timeout")
spring.commons.rest.template.timeout ese - era un . error de tipeo

2020-09-09 11:09 UTC, damianwajser approved these changes

2020-09-09 11:10 UTC, merged